export const pages = {
  HOME: "/",
  ABOUT: "/about/",
  DELIVERY: "/delivery/",
  PAY: "/pay/",
  PARTNERS: "/partners/",
  VACANCIES: "/vacancies/",
  BLOG: "/blog/",
  CONTACTS: "/contacts/",
  CATALOG: "/catalog/",
  TAG: "/tag/",
  CART: "/cart/",
  POLICY: "/policy/",
  SUCCESS: "/success/",
};

export const activeInLang = {
  ru: [
    pages.HOME,
    pages.ABOUT,
    pages.DELIVERY,
    pages.PAY,
    pages.PARTNERS,
    pages.VACANCIES,
    pages.BLOG,
    pages.CONTACTS,
    pages.CATALOG,
    pages.CART,
    pages.POLICY,
    pages.SUCCESS,
  ],
  en: [
    pages.HOME,
    pages.ABOUT,
    pages.DELIVERY,
    pages.PAY,
    pages.PARTNERS,
    pages.BLOG,
    pages.CONTACTS,
    pages.CATALOG,
    pages.CART,
    pages.POLICY,
    pages.SUCCESS,
  ],
  tr: [
    pages.HOME,
    pages.ABOUT,
    pages.DELIVERY,
    pages.PAY,
    pages.PARTNERS,
    pages.BLOG,
    pages.CONTACTS,
    pages.CATALOG,
    pages.CART,
    pages.POLICY,
    pages.SUCCESS,
  ],
  zh: [
    pages.HOME,
    pages.ABOUT,
    pages.DELIVERY,
    pages.PAY,
    pages.PARTNERS,
    pages.BLOG,
    pages.CONTACTS,
    pages.CATALOG,
    pages.CART,
    pages.POLICY,
    pages.SUCCESS,
  ],
};
